### ISSUE TITLE
`fieldData` renamed to `fromField`?

### ISSUE THREAD

**Issue by PMunch** [coffeepots/odbc#10]
While reading through the README I came across (this)[https://github.com/coffeepots/odbc/blame/master/README.md#L148] line which seems to indicate that there is a procedure named `fieldData`, but trying to use it shows that it doesn't exist. After poking through the source I found the `fromField` procedure which seems to do the same thing. Not sure if it was renamed or something else happened, but it should be corrected in the README.

**Comment by coffeepots** [comment]
Thanks for this @PMunch. I ended up making a few updates to unify the API after looking for `fieldData`.

The `data` proc is now the defacto access proc and `fromField` has been deprecated as was just another name for `data`.
