### ISSUE TITLE
The length of the table changed while iterating over it 

### ISSUE THREAD

**Issue by mprkins** [coffeepots/odbc#14]
#v0.19: {200: "a lot", 1: "one", 2: "two", 3: "three", 20: "a lot"}
#v0.20: Error: unhandled exception: the length of the table changed while iterating over it [AssertionError]

https://github.com/coffeepots/odbc/blob/9af9e7388153972515349becb4c6c378f99e2d8b/odbc/odbcconnections.nim#L56

**Comment by coffeepots** [comment]
@mprkins I've been trying to reproduce this with no luck. When does it happen, is it at program exit or when running? The line is called by the GC finaliser for connections and these are kind of an old way of doing things in Nim now. Are you running queries on different threads?

**Comment by mprkins** [comment]
@coffeepots 

hmm I dont think I am doing anything special.

Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-13
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: f16bb4d85b724f03b41c4dd104b439fa96c2fda4
active boot switches: -d:release

code to reproduce

```nim
import ./odbc/odbc, json, strformat

var
  con = newODBCConnection()
  qry = newQuery(con)

con.driver = "SQL Server Native Client 11.0"
con.host = r""
con.port = 1433
con.database = ""
con.integratedSecurity = false
con.userName = ""
con.password = ""

qry.statement = fmt"select * from version"

if not con.connect:
  echo "Cant connect"

var results = qry.executeFetch
echo results.toJson.pretty
```

errors:

C:\nim_code\TestCode>test_connector.exe
C:\nim_code\TestCode\test_connector.nim(72) test_connector
C:\nim_code\TestCode\odbc\odbc.nim(303) executeFetch
C:\nim_code\TestCode\odbc\odbc.nim(183) fetch
C:\nim_code\TestCode\odbc\odbc.nim(165) fetchRow
C:\nim_code\TestCode\odbc\odbc\odbctypes.nim(172) initSQLData
C:\Nim\lib\system\assign.nim(243) FieldDiscriminantCheck
C:\Nim\lib\system\fatal.nim(39) sysFatal
Error: unhandled exception: assignment to discriminant changes object branch; compile with -d:nimOldCaseObjects for a transition period [FieldError]
C:\nim_code\TestCode\test_connector.nim(72) test_connector
C:\nim_code\TestCode\odbc\odbc.nim(307) executeFetch
C:\Nim\lib\pure\collections\tables.nim(669) finaliseConnections
C:\Nim\lib\system\assertions.nim(27) failedAssertImpl
C:\Nim\lib\system\assertions.nim(20) raiseAssert
C:\Nim\lib\system\fatal.nim(39) sysFatal
Error: unhandled exception: C:\Nim\lib\pure\collections\tables.nim(669, 13) `len(t) ==
    L` the length of the table changed while iterating over it [AssertionError]


with the -d:nimOldCaseObjects switch i get the same error though

**Comment by coffeepots** [comment]
Ah I think this has been fixed recently, initSQLData should now look like [this](https://github.com/coffeepots/odbc/blob/a2810a03d25f719408006881044e6328f6fdd3a3/odbc/odbctypes.nim#L170).

If you fetch the latest version is the issue still present? Your example run to the point of reporting that it can't connect for me.

**Comment by mprkins** [comment]
Thanks a lot!!!

I did git clone again the odbc repo and it seems okay now.
Much appreciated.
