### ISSUE TITLE
odbctypes.nim(107)       toDataType Error: unhandled exception: Unsupported type when setting value: ctGUID [ODBCUnsupportedTypeException:ObjectType]

### ISSUE THREAD

**Issue by mprkins** [coffeepots/odbc#17]
Hello,
I am getting the following exception when doing simple select * from table.

The table is 

| ColumnName  | DataType |
| ------------- | ------------- |
| uidMessageID     | uniqueidentifier |
| UserName         | sysname          |
| PublishingServer | sysname          |
| OriginatorSID    | sysname          |
| OriginatorPID    | nvarchar         |
| dtTimeStamp      | datetime         |
| dtExpiration     | datetime         |
| nvcMessageType   | nvarchar         |
| nNumParts        | int              |
| uidBodyPartID    | uniqueidentifier |
| nvcBodyPartName  | nvarchar         |
| nCounter         | int              |
| imgContext       | image            |

This is MS SQL server 11.0.5388.0

**Comment by coffeepots** [comment]
GUID was on the TODO list as it needs some helper procs. I've got a basic version working already so this is now WIP :)

**Comment by mprkins** [comment]
Thanks a lot. I am sorry I cant contribute. Your driver code looks non trivial to me and my skill level is not anywhere close to understanding the intricacies of that code :/.

Do you have any resources I could use to learn how to do stuff like this?

**Comment by coffeepots** [comment]
It's a fairly simple change in principle, basically the case [statements](https://github.com/coffeepots/odbc/blob/a2810a03d25f719408006881044e6328f6fdd3a3/odbc/odbctypes.nim#L106) around data types need updating so they support mapping the table column type `ctGUID` to the appropiate Nim type (which currently doesn't exist). I was thinking of just converting it to string but really it needs it's own proper [16-byte](https://en.wikipedia.org/wiki/Universally_unique_identifier) storage added to `SQLDataType` as `dtGuid` for efficiency reasons so it's a bit more involved.

In the mean time, if you don't mind specifying individual fields, you can convert `uniqueidentifier`/GUID fields to string within the SQL query using `CONVERT(char(36), myGuidField)` or `CAST(myGuidField AS char(36))` to allow reading the table. For example using the library:

```nim
echo connection.dbq("SELECT CONVERT(char(36), myGuidField) FROM myTable")
```

Unfortunately you have to manually wrap those fields and can't use `SELECT * FROM ...` with any table using `uniqueidentifier` until there's GUID support.

For a general introduction to using ODBC at the API level [this](https://www.easysoft.com/developer/languages/c/odbc_tutorial.html) covers most of it. It's in C and assumes unix but the principles are the same for Nim and Windows. Most of the work of this library is just wrapping buffers to either tell ODBC what to do, or to recieve info back again!  :)

**Comment by coffeepots** [comment]
Hi @mprkins, I've added native support for GUIDs. No more converting to string required and you can now use `SELECT *` on tables that have the `uniqueidentifier` field.

If you were using the `uniqueidentifier` converted to string as mentioned above, it should now be faster and take up much less space (16 vs 36 bytes). You can set up a GUID field or parameter from a string value with the `guid` proc.

I think the `image` field you have in your table will work as a binary type, but let me know if you encounter any issues :)
