### ISSUE TITLE
odbchandles.nim(44, 35) Error: type mismatch

### ISSUE THREAD

**Issue by heigos** [coffeepots/odbc#18]
Hi!
After upgrading to Nim Version 1.2.6, it does not compile anymore.

> odbchandles.nim(44, 35) Error: type mismatch: got <SqlHEnv, TSqlInteger, TSqlInteger, int literal(0)>
but expected one of:
proc SQLSetEnvAttr(EnvironmentHandle: SqlHEnv; Attribute: TSqlInteger;
                  Value: SqlPointer; StringLength: TSqlInteger): TSqlSmallInt
  first type mismatch at position: 3
  required type for Value: SqlPointer
  but expression 'odbcVersion' is of type: TSqlInteger
expression: SQLSetEnvAttr(envHandle, TSqlInteger(200), odbcVersion, 0)

**Comment by coffeepots** [comment]
@heigos the lastest version is now compatible with Nim 1.4. Let me know if you encounter any issues.
