### ISSUE TITLE
nvarchar(MAX) gets truncated

### ISSUE THREAD

**Issue by heigos** [coffeepots/odbc#19]
nvarchar(MAX) field gets truncated to 2 characters.

> ODBC call SQLGetData returned non-success: success with info (1)
state = '01004' (err=0) message = '[Microsoft][SQL Server Native Client 11.0]String data, right truncation'

**Comment by coffeepots** [comment]
Hi @heigos, this should be fixed with the latest version. Let me know if you have any further issues!

**Comment by heigos** [comment]
hi!
nvarchar(4000) works fine, but when I change that same column to nvarchar(MAX), it fails at executeFetch:

> \tests\odbc.nim(335) executeFetch
\tests\odbc.nim(307) setupColumns
\tests\odbc.nim(295) getColDetails
\nim\lib\system\fatal.nim(49) sysFatal
Error: unhandled exception: value out of range [RangeDefect]
