### ISSUE TITLE
Not compilable on 0.18.1 674bd7bfad100a07e051e0a310bcf0a64c355a79

### ISSUE THREAD

**Issue by mprkins** [coffeepots/odbc#5]
odbc\odbcparams.nim(163, 36) Error: type mismatch: got <int, SqlUSmallInt, SqlUSmallInt, SqlUSmallInt, SqlUSmallInt, SqlUSmallInt, SqlUSmallInt>
but expected one of:
proc initInterval(seconds, minutes, hours, days, months, years: int = 0): TimeInterval

expression: initInterval(ms, timestamp.Second, timestamp.Minute, timestamp.Hour, timestamp.Day,
             timestamp.Month, timestamp.Year)

**Comment by coffeepots** [comment]
This is due to the `times` module changing it's `time` representation. I have a branch in the works that fixes it, but it still needs some work.

**Comment by mprkins** [comment]
Thanks. The latest commits made it work.

**Comment by coffeepots** [comment]
Note that with this commit I've changed where fields are stored - they're now in the `SQLQuery` object, accessible with the `fields` proc.

Also, currently the nanosecond portion of times isn't being populated: #6
