### ISSUE TITLE
The nil state for strings/seqs got removed from 0.19.0

### ISSUE THREAD

**Issue by mprkins** [coffeepots/odbc#7]
The use of isNil is raising an error when compiling programs using winim. The temp solution is to use --nilseqs:on for a transition period as advised in the release notes of Nim 0.19.0. before this is adapted in winim.

**Comment by coffeepots** [comment]
Oh hey I just did an update for this before I saw this issue :) Should work with 0.19 now.

**Comment by mprkins** [comment]
Great. Thanks!
